name: DashPack
version: '1.0.0'
main: me.justahuman.projectkorra.dashpack.DashPack
api-version: '1.21'
authors: [ JustAHuman ]
depend: [ ProjectKorra ]
website: https://github.com/JustAHuman-xD/DashPack
